In [1]:
import pandas as pd
import os

In [2]:
cwd = os.getcwd()
timeseries_df = pd.read_csv(cwd + "/datasets/timeseries_with_wav.csv")
timeseries_df = timeseries_df.drop('Unnamed: 0', axis=1)

In [3]:
timeseries_df.drop('datetime', axis=1).corr()

,Millis,ECG,IR,RED,patient,rate_min,rate_max,rate_std,rate_avg,rate_25%,rate_50%,rate_75%
Millis,1.000000,0.006780,0.002464,0.000326,0.001208,-0.001189,0.000789,0.001878,-0.000193,-0.001003,-0.000183,0.000668
ECG,0.006780,1.000000,-0.076462,-0.088521,-0.331177,-0.000921,0.002249,0.002560,0.000046,-0.001122,-0.000398,0.001021
IR,0.002464,-0.076462,1.000000,0.803839,0.256924,-0.041006,0.040226,0.059375,0.000006,-0.024251,-0.000094,0.023896
RED,0.000326,-0.088521,0.803839,1.000000,0.278786,-0.013951,0.013636,0.020281,-0.000006,-0.008307,0.000104,0.008089
patient,0.001208,-0.331177,0.256924,0.278786,1.000000,-0.020882,0.019263,0.028234,0.000059,-0.011157,0.000736,0.011130
rate_min,-0.001189,-0.000921,-0.041006,-0.013951,-0.020882,1.000000,0.103698,-0.654880,0.724805,0.932046,0.703643,0.377429
rate_max,0.000789,0.002249,0.040226,0.013636,0.019263,0.103698,1.000000,0.674807,0.729323,0.376738,0.703120,0.931181
rate_std,0.001878,0.002560,0.059375,0.020281,0.028234,-0.654880,0.674807,1.000000,0.017213,-0.411072,0.013534,0.434629
rate_avg,-0.000193,0.000046,0.000006,-0.000006,0.000059,0.724805,0.729323,0.017213,1.000000,0.901749,0.991224,0.905438
rate_25%,-0.001003,-0.001122,-0.024251,-0.008307,-0.011157,0.932046,0.376738,-0.411072,0.901749,1.000000,0.895386,0.634972
rate_50%,-0.000183,-0.000398,-0.000094,0.000104,0.000736,0.703643,0.703120,0.013534,0.991224,0.895386,1.000000,0.896741
rate_75%,0.000668,0.001021,0.023896,0.008089,0.011130,0.377429,0.931181,0.434629,0.905438,0.634972,0.896741,1.000000

In [4]:
report_df = pd.read_csv(cwd + "/datasets/report.csv")
report_df = report_df.drop('Unnamed: 0', axis=1)
info_df = pd.read_csv(cwd + "/datasets/patient_info.csv")
info_df = info_df.drop('Unnamed: 0', axis=1)

In [5]:
report_df.columns

Index(['patient', 'patient_name', 'application_date', 'patient_no',
       'report_date', 'age', 'sex', 'practicing_doctor', 'requesting_section',
       'preliminary_diagnosis', 'aortic_root', 'ascending_aorta',
       'end_diastolic_diameter', 'end_systolic_diameter', 'injection_fraction',
       'septum', 'back_wall', 'hatchway_speed', 'local_wall',
       'left_atrium_size', 'right_atrium_size', 'diastolic_diameter', 's_val',
       'tapse', 'visual_systolic_function', 'e_a', 'deceleration_time', 'ivrz',
       'e_septal', 'e_lateral', 'systolic_pulmonary_artery_pressure',
       'result'],
      dtype='object')

In [6]:
report_df.head()

,patient,patient_name,application_date,patient_no,report_date,age,sex,practicing_doctor,requesting_section,preliminary_diagnosis,...,s_val,tapse,visual_systolic_function,e_a,deceleration_time,ivrz,e_septal,e_lateral,systolic_pulmonary_artery_pressure,result
0,3,VEZİR YAŞAR,NaN,2022238881,2023-10-18 16:08:33,60,E,NaN,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,50,NaN,NaN,LA: 35X42X52
1,23,SARAYNAZ GÖKBAŞİ,NaN,2009334527,2023-10-20 15:05:57,76,K,NaN,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,50,NaN,NaN,LA DİLATASYONU (LA: 41X45X55)\nHAFİF TY
2,25,HÜSNİYE OLAM,NaN,2009444601,2023-10-20 16:38:37,63,K,NaN,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,50,NaN,NaN,LA DİLATASYONU (LA: 44X50X56)\nMİTRAL ANULUS K...
3,27,İLHAMİ YEŞİL,NaN,2009392364,2023-10-23 15:43:41,57,E,NaN,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,50,NaN,NaN,LA DİLATASYONU (LA: 40X43X48)\nSOL VENTRİKÜL H...
4,22,HANİFE ÇİÇEK,NaN,2010223331,2023-10-20 14:57:16,65,K,NaN,NaN,NaN,...,NaN,NaN,0,NaN,NaN,NaN,50,NaN,NaN,ASENDAN AORTADA DİLATASYON\nLA DİLATASYONU (LA...

In [7]:
info_df.head()

,id,name_surname,identification_number,date,HT,DM,HL,KAH,KOAH,KBY,KC HST,NOT,complaint,weight,height,systolic_pressure,diastolic_pressure
0,1,NURCAN TANTÜR,63115237952,2023-10-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,158.0,95.0,141.0,77.0
1,2,MÜNÜR ÇAPKINLAR,34333168786,2023-10-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,170.0,83.0,132.0,80.0
2,3,VEZİR YAŞAR,31936213592,2023-10-18,0.0,1.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,165.0,73.0,39.0,77.0
3,4,MENŞURE ÇİNİCİ,25627707118,2023-10-18,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,78.0,146.0,90.0
4,5,OĞUZHAN GÜLOĞULLARI,20023624076,2023-10-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,ATGA,178.0,70.0,32.0,62.0

In [8]:
merge_df = pd.merge(report_df, info_df, left_on='patient', right_on='id')
merge_df

,patient,patient_name,application_date,patient_no,report_date,age,sex,practicing_doctor,requesting_section,preliminary_diagnosis,...,KAH,KOAH,KBY,KC HST,NOT,complaint,weight,height,systolic_pressure,diastolic_pressure
0,3,VEZİR YAŞAR,NaN,2022238881,2023-10-18 16:08:33,60,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,165.0,73.0,39.0,77.0
1,23,SARAYNAZ GÖKBAŞİ,NaN,2009334527,2023-10-20 15:05:57,76,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,155.0,60.0,151.0,38.0
2,25,HÜSNİYE OLAM,NaN,2009444601,2023-10-20 16:38:37,63,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ÇARPINTI,158.0,95.0,174.0,80.0
3,27,İLHAMİ YEŞİL,NaN,2009392364,2023-10-23 15:43:41,57,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,ATGA,167.0,98.0,137.0,79.0
4,22,HANİFE ÇİÇEK,NaN,2010223331,2023-10-20 14:57:16,65,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,AF,ATGA,150.0,104.0,135.0,70.0
5,19,MURAT KARAYEL,NaN,2013115566,2023-10-20 14:08:10,47,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,171.0,87.0,132.0,78.0
6,14,YUSUF TURHAN,NaN,2010268947,2023-10-19 15:40:13,66,E,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,172.0,82.0,140.0,85.0
7,13,DURMUŞ ÖZTÜRK,NaN,2009166562,2023-10-19 15:32:36,51,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,175.0,87.0,137.0,81.0
8,41,HACER BİNALİOĞLU,NaN,2010361726,2023-10-27 15:57:16,64,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,163.0,105.0,173.0,94.0
9,31,İDRİS SERT,NaN,2009070964,2023-10-25 15:37:47,56,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,177.0,104.0,154.0,84.0
10,29,NÜSRET GÖKÇE,NaN,2016119682,2023-10-23 16:00:13,62,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,CABG,ATGA,172.0,96.0,161.0,77.0
11,8,LÜTFİYE ADALI,NaN,2016213502,2023-10-18 15:33:01,58,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,AVR+MVR,NaN,156.0,70.0,137.0,64.0
12,39,ERDOĞAN YILMAZ,NaN,2010027126,2023-10-27 15:42:42,56,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,167.0,87.0,140.0,68.0
13,40,AYŞE YILDIRIM,NaN,2009345536,2023-10-27 15:48:29,59,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,160.0,78.0,174.0,97.0
14,10,KADİR YALÇIN,NaN,2023131335,2023-10-19 10:59:43,65,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,171.0,60.0,113.0,74.0
15,17,ŞAHİDE NİYAZOĞLU,NaN,2014262020,2023-10-20 11:15:00,59,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,158.0,72.0,153.0,82.0
16,2,MÜNÜR ÇAPKINLAR,NaN,2010173740,2023-10-18 09:51:52,62,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,170.0,83.0,132.0,80.0
17,1,NURCAN TANTUR,NaN,2009001287,2023-10-18 09:37:37,53,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,158.0,95.0,141.0,77.0
18,34,SÜHEYLA OKUMUŞ,NaN,2009416786,2023-10-25 16:02:41,59,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,165.0,75.0,136.0,71.0
19,21,AZİZE OPUZ,NaN,2009483173,2023-10-20 14:38:03,71,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,AVR+SİSTOLİK ÜFÜRÜM,NaN,158.0,98.0,180.0,89.0
20,12,EMİNE ARINÇ,NaN,2006076436,2023-10-19 15:25:55,74,K,NaN,NaN,NaN,...,1.0,0.0,0.0,1.0,CABG,NaN,155.0,68.0,201.0,91.0
21,38,GÜLSİMET TURHANER,NaN,2009563351,2023-10-27 15:35:33,61,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,160.0,71.0,177.0,104.0
22,37,NAZMİYE MÜMİNOĞLU,NaN,2022030986,2023-10-25 16:31:31,69,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ÇARPINTI,157.0,611.0,134.0,74.0
23,26,TÜLAY BAKIR,NaN,2011043793,2023-10-23 15:35:42,48,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,150.0,58.0,118.0,75.0
24,5,OĞUZHAN GÜLOĞULLARI,NaN,2010287204,2023-10-18 14:23:58,25,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,178.0,70.0,32.0,62.0
25,7,SEVDA UYSAL,NaN,2011185275,2023-10-18 15:03:32,54,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,NaN,143.0,75.0,186.0,95.0
26,32,İZZET SOYLU,NaN,2017452619,2023-10-25 15:48:04,55,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,185.0,100.0,140.0,100.0
27,15,EROL ALTUNKAYA,NaN,2009122381,2023-10-19 15:47:43,50,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,165.0,85.0,149.0,87.0
28,28,HACI ERDAL,NaN,2017073268,2023-10-23 15:51:17,59,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,CABG,ATGA,170.0,98.0,137.0,78.0
29,16,LEYLA YAĞMUR,NaN,2006549471,2023-10-19 15:57:46,63,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,157.0,73.0,171.0,83.0
30,24,NEZAHAT YILDIRIM,NaN,2009480173,2023-10-20 16:28:00,67,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,EFOR DİSPNESİ,161.0,77.0,135.0,77.0
31,33,HATUN DOKMUŞ,NaN,2009387926,2023-10-25 15:54:22,48,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,163.0,76.0,NaN,NaN
32,20,AHMET ÖRS,NaN,2006630512,2023-10-20 14:18:06,70,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,CABG,NaN,165.0,83.0,139.0,77.0
33,9,SELAMİ KOŞUCU,NaN,2013025887,2023-10-18 15:40:07,48,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,175.0,75.0,131.0,83.0
34,11,HANIM YILMAZ,NaN,2011191666,2023-10-19 15:15:34,65,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,CABG,NaN,162.0,75.0,177.0,98.0
35,18,NERİMAN GÜLER,NaN,2009093536,2023-10-20 09:45:28,71,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,155.0,70.0,139.0,73.0
36,35,NURAY KABA,NaN,2013167794,2023-10-25 16:12:15,41,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,159.0,74.0,115.0,78.0
37,4,MENŞURE ÇİNİCİ,NaN,2017221642,2023-10-18 14:08:18,59,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,78.0,146.0,90.0
38,36,YUSUF SAÇLI,NaN,2009587082,2023-10-25 16:21:59,59,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,ATGA,163.0,63.0,NaN,NaN
39,6,SENFİNAZ ARAS,NaN,2010216741,2023-10-18 14:46:20,68,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,NaN,155.0,81.0,45.0,86.0
40,30,FERİDE GÖZALAN,NaN,2012181508,2023-10-23 16:08:47,58,K,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,PM+,ATGA,NaN,NaN,108.0,56.0

In [9]:
merge_df.dtypes

patient                                 int64
patient_name                           object
application_date                      float64
patient_no                              int64
report_date                            object
age                                     int64
sex                                    object
practicing_doctor                     float64
requesting_section                    float64
preliminary_diagnosis                 float64
aortic_root                             int64
ascending_aorta                         int64
end_diastolic_diameter                float64
end_systolic_diameter                   int64
injection_fraction                      int64
septum                                  int64
back_wall                               int64
hatchway_speed                        float64
local_wall                            float64
left_atrium_size                        int64
right_atrium_size                       int64
diastolic_diameter                    float64
s_val                                 float64
tapse                                 float64
visual_systolic_function                int64
e_a                                   float64
deceleration_time                     float64
ivrz                                  float64
e_septal                                int64
e_lateral                             float64
systolic_pulmonary_artery_pressure    float64
result                                 object
id                                      int64
name_surname                           object
identification_number                   int64
date                                   object
HT                                    float64
DM                                    float64
HL                                    float64
KAH                                   float64
KOAH                                  float64
KBY                                   float64
KC HST                                float64
NOT                                    object
complaint                              object
weight                                float64
height                                float64
systolic_pressure                     float64
diastolic_pressure                    float64
dtype: object

In [10]:
merge_df.isna().sum()

patient                                0
patient_name                           0
application_date                      41
patient_no                             0
report_date                            0
age                                    0
sex                                    0
practicing_doctor                     41
requesting_section                    41
preliminary_diagnosis                 41
aortic_root                            0
ascending_aorta                        0
end_diastolic_diameter                41
end_systolic_diameter                  0
injection_fraction                     0
septum                                 0
back_wall                              0
hatchway_speed                        41
local_wall                            41
left_atrium_size                       0
right_atrium_size                      0
diastolic_diameter                    40
s_val                                 41
tapse                                 41
visual_systolic_function               0
e_a                                   41
deceleration_time                     41
ivrz                                  41
e_septal                               0
e_lateral                             41
systolic_pulmonary_artery_pressure    35
result                                 0
id                                     0
name_surname                           0
identification_number                  0
date                                   0
HT                                     1
DM                                     1
HL                                     1
KAH                                    1
KOAH                                   1
KBY                                    1
KC HST                                 1
NOT                                   32
complaint                             20
weight                                 2
height                                 1
systolic_pressure                      2
diastolic_pressure                     2
dtype: int64

In [11]:
merge_df = merge_df.drop(columns=['name_surname', 'date'])

In [12]:
merge_df

,patient,patient_name,application_date,patient_no,report_date,age,sex,practicing_doctor,requesting_section,preliminary_diagnosis,...,KAH,KOAH,KBY,KC HST,NOT,complaint,weight,height,systolic_pressure,diastolic_pressure
0,3,VEZİR YAŞAR,NaN,2022238881,2023-10-18 16:08:33,60,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,165.0,73.0,39.0,77.0
1,23,SARAYNAZ GÖKBAŞİ,NaN,2009334527,2023-10-20 15:05:57,76,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,155.0,60.0,151.0,38.0
2,25,HÜSNİYE OLAM,NaN,2009444601,2023-10-20 16:38:37,63,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ÇARPINTI,158.0,95.0,174.0,80.0
3,27,İLHAMİ YEŞİL,NaN,2009392364,2023-10-23 15:43:41,57,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,ATGA,167.0,98.0,137.0,79.0
4,22,HANİFE ÇİÇEK,NaN,2010223331,2023-10-20 14:57:16,65,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,AF,ATGA,150.0,104.0,135.0,70.0
5,19,MURAT KARAYEL,NaN,2013115566,2023-10-20 14:08:10,47,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,171.0,87.0,132.0,78.0
6,14,YUSUF TURHAN,NaN,2010268947,2023-10-19 15:40:13,66,E,NaN,NaN,NaN,...,0.0,1.0,0.0,0.0,NaN,NaN,172.0,82.0,140.0,85.0
7,13,DURMUŞ ÖZTÜRK,NaN,2009166562,2023-10-19 15:32:36,51,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,175.0,87.0,137.0,81.0
8,41,HACER BİNALİOĞLU,NaN,2010361726,2023-10-27 15:57:16,64,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,163.0,105.0,173.0,94.0
9,31,İDRİS SERT,NaN,2009070964,2023-10-25 15:37:47,56,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,177.0,104.0,154.0,84.0
10,29,NÜSRET GÖKÇE,NaN,2016119682,2023-10-23 16:00:13,62,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,CABG,ATGA,172.0,96.0,161.0,77.0
11,8,LÜTFİYE ADALI,NaN,2016213502,2023-10-18 15:33:01,58,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,AVR+MVR,NaN,156.0,70.0,137.0,64.0
12,39,ERDOĞAN YILMAZ,NaN,2010027126,2023-10-27 15:42:42,56,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,167.0,87.0,140.0,68.0
13,40,AYŞE YILDIRIM,NaN,2009345536,2023-10-27 15:48:29,59,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,160.0,78.0,174.0,97.0
14,10,KADİR YALÇIN,NaN,2023131335,2023-10-19 10:59:43,65,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,171.0,60.0,113.0,74.0
15,17,ŞAHİDE NİYAZOĞLU,NaN,2014262020,2023-10-20 11:15:00,59,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,158.0,72.0,153.0,82.0
16,2,MÜNÜR ÇAPKINLAR,NaN,2010173740,2023-10-18 09:51:52,62,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,170.0,83.0,132.0,80.0
17,1,NURCAN TANTUR,NaN,2009001287,2023-10-18 09:37:37,53,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,158.0,95.0,141.0,77.0
18,34,SÜHEYLA OKUMUŞ,NaN,2009416786,2023-10-25 16:02:41,59,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,165.0,75.0,136.0,71.0
19,21,AZİZE OPUZ,NaN,2009483173,2023-10-20 14:38:03,71,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,AVR+SİSTOLİK ÜFÜRÜM,NaN,158.0,98.0,180.0,89.0
20,12,EMİNE ARINÇ,NaN,2006076436,2023-10-19 15:25:55,74,K,NaN,NaN,NaN,...,1.0,0.0,0.0,1.0,CABG,NaN,155.0,68.0,201.0,91.0
21,38,GÜLSİMET TURHANER,NaN,2009563351,2023-10-27 15:35:33,61,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,160.0,71.0,177.0,104.0
22,37,NAZMİYE MÜMİNOĞLU,NaN,2022030986,2023-10-25 16:31:31,69,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ÇARPINTI,157.0,611.0,134.0,74.0
23,26,TÜLAY BAKIR,NaN,2011043793,2023-10-23 15:35:42,48,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,150.0,58.0,118.0,75.0
24,5,OĞUZHAN GÜLOĞULLARI,NaN,2010287204,2023-10-18 14:23:58,25,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,178.0,70.0,32.0,62.0
25,7,SEVDA UYSAL,NaN,2011185275,2023-10-18 15:03:32,54,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,NaN,143.0,75.0,186.0,95.0
26,32,İZZET SOYLU,NaN,2017452619,2023-10-25 15:48:04,55,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,185.0,100.0,140.0,100.0
27,15,EROL ALTUNKAYA,NaN,2009122381,2023-10-19 15:47:43,50,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,165.0,85.0,149.0,87.0
28,28,HACI ERDAL,NaN,2017073268,2023-10-23 15:51:17,59,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,CABG,ATGA,170.0,98.0,137.0,78.0
29,16,LEYLA YAĞMUR,NaN,2006549471,2023-10-19 15:57:46,63,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,157.0,73.0,171.0,83.0
30,24,NEZAHAT YILDIRIM,NaN,2009480173,2023-10-20 16:28:00,67,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,EFOR DİSPNESİ,161.0,77.0,135.0,77.0
31,33,HATUN DOKMUŞ,NaN,2009387926,2023-10-25 15:54:22,48,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,163.0,76.0,NaN,NaN
32,20,AHMET ÖRS,NaN,2006630512,2023-10-20 14:18:06,70,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,CABG,NaN,165.0,83.0,139.0,77.0
33,9,SELAMİ KOŞUCU,NaN,2013025887,2023-10-18 15:40:07,48,E,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,175.0,75.0,131.0,83.0
34,11,HANIM YILMAZ,NaN,2011191666,2023-10-19 15:15:34,65,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,CABG,NaN,162.0,75.0,177.0,98.0
35,18,NERİMAN GÜLER,NaN,2009093536,2023-10-20 09:45:28,71,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,155.0,70.0,139.0,73.0
36,35,NURAY KABA,NaN,2013167794,2023-10-25 16:12:15,41,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,ATGA,159.0,74.0,115.0,78.0
37,4,MENŞURE ÇİNİCİ,NaN,2017221642,2023-10-18 14:08:18,59,K,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,NaN,NaN,78.0,146.0,90.0
38,36,YUSUF SAÇLI,NaN,2009587082,2023-10-25 16:21:59,59,E,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,ATGA,163.0,63.0,NaN,NaN
39,6,SENFİNAZ ARAS,NaN,2010216741,2023-10-18 14:46:20,68,K,NaN,NaN,NaN,...,1.0,0.0,0.0,0.0,NaN,NaN,155.0,81.0,45.0,86.0
40,30,FERİDE GÖZALAN,NaN,2012181508,2023-10-23 16:08:47,58,K,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,PM+,ATGA,NaN,NaN,108.0,56.0

In [13]:
lab_df = pd.read_csv((cwd + "/datasets/lab2.csv"))
lab_df = lab_df.drop('Unnamed: 0', axis=1)

lab_df.head()

,patient,ldl,vldl,gfr,bilirubin_in,aks,bun,crea,tri,colestrol,...,baso_hatch,t3,t4,tsh,folat,b12,TROPONIN I,CK-MB,BNP,HbA1C
0,3,"132,5","27,8","90,8","0,87",372,14.0,"0,93",139.0,202.0,...,"0,02","3,41","1,37","1,03","7,4",407,"15,8","1,1","23,6",106.0
1,23,"170,2","21,4","74,6","0,16",87,21.0,"0,78",107.0,254.0,...,"0,02","2,61","0,91","3,69","9,4",290,"4,4",NaN,"70,3",35.0
2,25,"128,4","62,6","76,94","0,06",242,18.0,"0,82",313.0,231.0,...,"0,04","2,9","1,12","0,25","5,3",195,"3,9","2,1",NaN,75.0
3,27,NaN,"106,8","77,95","0,81",93,16.0,"1,08",534.0,207.0,...,"0,06","3,1","0,86","1,15","6,2",635,"3,5","1,3",NaN,37.0
4,22,"71,9","19,2","72,64","0,34",80,18.0,"0,85",96.0,130.0,...,"0,07","2,71","0,92","3,23","13,3",509,"2,9","1,1","224,6",40.0

In [14]:
merge_df = pd.merge(merge_df, lab_df, left_on='patient', right_on='patient')
merge_df

,patient,patient_name,application_date,patient_no,report_date,age,sex,practicing_doctor,requesting_section,preliminary_diagnosis,...,baso_hatch,t3,t4,tsh,folat,b12,TROPONIN I,CK-MB,BNP,HbA1C
0,3,VEZİR YAŞAR,NaN,2022238881,2023-10-18 16:08:33,60,E,NaN,NaN,NaN,...,"0,02","3,41","1,37","1,03","7,4",407,"15,8","1,1","23,6",106.0
1,23,SARAYNAZ GÖKBAŞİ,NaN,2009334527,2023-10-20 15:05:57,76,K,NaN,NaN,NaN,...,"0,02","2,61","0,91","3,69","9,4",290,"4,4",NaN,"70,3",35.0
2,25,HÜSNİYE OLAM,NaN,2009444601,2023-10-20 16:38:37,63,K,NaN,NaN,NaN,...,"0,04","2,9","1,12","0,25","5,3",195,"3,9","2,1",NaN,75.0
3,27,İLHAMİ YEŞİL,NaN,2009392364,2023-10-23 15:43:41,57,E,NaN,NaN,NaN,...,"0,06","3,1","0,86","1,15","6,2",635,"3,5","1,3",NaN,37.0
4,22,HANİFE ÇİÇEK,NaN,2010223331,2023-10-20 14:57:16,65,K,NaN,NaN,NaN,...,"0,07","2,71","0,92","3,23","13,3",509,"2,9","1,1","224,6",40.0
5,19,MURAT KARAYEL,NaN,2013115566,2023-10-20 14:08:10,47,E,NaN,NaN,NaN,...,"0,01","3,34",NaN,"0,51","4,4",264,"1,3","1,1","11,8",54.0
6,14,YUSUF TURHAN,NaN,2010268947,2023-10-19 15:40:13,66,E,NaN,NaN,NaN,...,"0,04","3,21","1,12","0,5",NaN,334,"3,8","0,8","44,5",26.0
7,13,DURMUŞ ÖZTÜRK,NaN,2009166562,2023-10-19 15:32:36,51,E,NaN,NaN,NaN,...,"0,02","2,92","0,88","2,65","4,5",166,"1,8","1,2",NaN,25.0
8,41,HACER BİNALİOĞLU,NaN,2010361726,2023-10-27 15:57:16,64,K,NaN,NaN,NaN,...,"0,02","2,39","0,82","4,32","7,8",335,14,"3,8","27,9",38.0
9,31,İDRİS SERT,NaN,2009070964,2023-10-25 15:37:47,56,E,NaN,NaN,NaN,...,"0,05","3,01","0,93","1,4","6,9",300,"3,1","1,4","18,9",27.0
10,29,NÜSRET GÖKÇE,NaN,2016119682,2023-10-23 16:00:13,62,E,NaN,NaN,NaN,...,"0,04","3,19","1,09","1,49","8,4",220,"4,9",NaN,"62,2",57.0
11,8,LÜTFİYE ADALI,NaN,2016213502,2023-10-18 15:33:01,58,K,NaN,NaN,NaN,...,"0,02","2,73","1,33","2,5","5,4",474,"2,1","2,8","54,4",41.0
12,39,ERDOĞAN YILMAZ,NaN,2010027126,2023-10-27 15:42:42,56,E,NaN,NaN,NaN,...,"0,04","3,13","0,97","1,5","5,1",333,"3,7","1,2","27,5",34.0
13,40,AYŞE YILDIRIM,NaN,2009345536,2023-10-27 15:48:29,59,K,NaN,NaN,NaN,...,"0,03","2,88","0,82","1,47","8,9",195,"0,7","1,3","23,8",51.0
14,10,KADİR YALÇIN,NaN,2023131335,2023-10-19 10:59:43,65,E,NaN,NaN,NaN,...,"0,03","2,71","1,25","1,2","4,3",188,"4,6","0,7","42,8",43.0
15,17,ŞAHİDE NİYAZOĞLU,NaN,2014262020,2023-10-20 11:15:00,59,K,NaN,NaN,NaN,...,"0,02","2,73","0,93","1,41","4,2",128,"2,7","2,5","47,6",39.0
16,2,MÜNÜR ÇAPKINLAR,NaN,2010173740,2023-10-18 09:51:52,62,E,NaN,NaN,NaN,...,"0,03","3,23","0,97",NaN,"5,7",252,"2,8","1,4","17,6",41.0
17,1,NURCAN TANTUR,NaN,2009001287,2023-10-18 09:37:37,53,K,NaN,NaN,NaN,...,"0,03","3,04","1,09","1,78","5,5",231,"4,9","1,4",86,52.0
18,34,SÜHEYLA OKUMUŞ,NaN,2009416786,2023-10-25 16:02:41,59,K,NaN,NaN,NaN,...,"0,01","3,16","1,1","0,7",NaN,260,"1,8","1,1","10,5",41.0
19,21,AZİZE OPUZ,NaN,2009483173,2023-10-20 14:38:03,71,K,NaN,NaN,NaN,...,"0,06","2,81","1,42","0,17","5,6",362,"3,9",NaN,"279,3",38.0
20,12,EMİNE ARINÇ,NaN,2006076436,2023-10-19 15:25:55,74,K,NaN,NaN,NaN,...,"0,06","2,62","0,79","4,79","10,4",106,"14,7","3,4","149,5",40.0
21,38,GÜLSİMET TURHANER,NaN,2009563351,2023-10-27 15:35:33,61,K,NaN,NaN,NaN,...,"0,04","2,93","0,9","0,74","4,5",224,"2,3","2,1","26,1",28.0
22,37,NAZMİYE MÜMİNOĞLU,NaN,2022030986,2023-10-25 16:31:31,69,K,NaN,NaN,NaN,...,NaN,"2,68","1,22","0,25","2,3",274,"2,5",NaN,"38,4",46.0
23,26,TÜLAY BAKIR,NaN,2011043793,2023-10-23 15:35:42,48,K,NaN,NaN,NaN,...,"0,03","3,01","0,85","2,21",NaN,381,"1,5",NaN,"23,9",42.0
24,5,OĞUZHAN GÜLOĞULLARI,NaN,2010287204,2023-10-18 14:23:58,25,E,NaN,NaN,NaN,...,"0,03","3,18","0,94","2,84","4,1",251,"3,8",NaN,"24,7",19.0
25,7,SEVDA UYSAL,NaN,2011185275,2023-10-18 15:03:32,54,K,NaN,NaN,NaN,...,"0,06","3,15","1,04","1,2","5,8",414,18,NaN,"96,2",106.0
26,32,İZZET SOYLU,NaN,2017452619,2023-10-25 15:48:04,55,E,NaN,NaN,NaN,...,"0,04","3,22","0,94","1,08","5,3",306,NaN,"4,9",NaN,38.0
27,15,EROL ALTUNKAYA,NaN,2009122381,2023-10-19 15:47:43,50,E,NaN,NaN,NaN,...,"0,02","1,52","1,13","0,56","6,6",174,"3,2","5,5",NaN,33.0
28,28,HACI ERDAL,NaN,2017073268,2023-10-23 15:51:17,59,E,NaN,NaN,NaN,...,"0,02","2,9","0,93","1,24","5,8",237,"3,3","2,7","12,7",65.0
29,16,LEYLA YAĞMUR,NaN,2006549471,2023-10-19 15:57:46,63,K,NaN,NaN,NaN,...,NaN,"3,01","0,87","1,5","7,7",358,"1,4","1,3",58,37.0
30,24,NEZAHAT YILDIRIM,NaN,2009480173,2023-10-20 16:28:00,67,K,NaN,NaN,NaN,...,"0,05","2,67","1,03","2,26","8,1",193,"2,5","1,6","49,5",56.0
31,33,HATUN DOKMUŞ,NaN,2009387926,2023-10-25 15:54:22,48,K,NaN,NaN,NaN,...,"0,02","2,56","1,08","0,97","7,7",243,"1,3","0,9","17,6",42.0
32,20,AHMET ÖRS,NaN,2006630512,2023-10-20 14:18:06,70,E,NaN,NaN,NaN,...,"0,02","2,76","0,92","0,91","8,1",168,"130,2",NaN,"351,3",83.0
33,9,SELAMİ KOŞUCU,NaN,2013025887,2023-10-18 15:40:07,48,E,NaN,NaN,NaN,...,"0,05","3,06","0,96","0,91","3,3",380,"3,9",NaN,"11,6",NaN
34,11,HANIM YILMAZ,NaN,2011191666,2023-10-19 15:15:34,65,K,NaN,NaN,NaN,...,"0,03","2,59","0,89","2,34","6,2",187,NaN,"1,2",44,39.0
35,18,NERİMAN GÜLER,NaN,2009093536,2023-10-20 09:45:28,71,K,NaN,NaN,NaN,...,NaN,"2,34","0,88","6,34","3,1",943,"1,5","2,4","16,7",43.0
36,35,NURAY KABA,NaN,2013167794,2023-10-25 16:12:15,41,K,NaN,NaN,NaN,...,"0,04","3,35","0,87","1,34",NaN,399,"0,9","0,8",30,35.0
37,4,MENŞURE ÇİNİCİ,NaN,2017221642,2023-10-18 14:08:18,59,K,NaN,NaN,NaN,...,"0,01","2,71","1,08","2,25","8,1",335,"1,9",NaN,"26,8",46.0
38,36,YUSUF SAÇLI,NaN,2009587082,2023-10-25 16:21:59,59,E,NaN,NaN,NaN,...,"0,09","2,93","1,12","1,04","3,4",295,"10,1","4,9","129,8",38.0
39,6,SENFİNAZ ARAS,NaN,2010216741,2023-10-18 14:46:20,68,K,NaN,NaN,NaN,...,"0,03","3,67","1,35","0,01","6,1",163,NaN,"0,8","90,4",114.0
40,30,FERİDE GÖZALAN,NaN,2012181508,2023-10-23 16:08:47,58,K,NaN,NaN,NaN,...,"0,05","1,98","1,24","1,33","5,5",231,"31,9","16,6","228,8",58.0

In [15]:
nan_list = merge_df.isna().sum().sort_values(ascending=False)

In [16]:
for column, count in nan_list.items():
    print(f"Column: {column}, NaN Count: {count}")

Column: application_date, NaN Count: 41
Column: preliminary_diagnosis, NaN Count: 41
Column: end_diastolic_diameter, NaN Count: 41
Column: practicing_doctor, NaN Count: 41
Column: requesting_section, NaN Count: 41
Column: e_a, NaN Count: 41
Column: deceleration_time, NaN Count: 41
Column: e_lateral, NaN Count: 41
Column: ivrz, NaN Count: 41
Column: hatchway_speed, NaN Count: 41
Column: local_wall, NaN Count: 41
Column: tapse, NaN Count: 41
Column: s_val, NaN Count: 41
Column: diastolic_diameter, NaN Count: 40
Column: systolic_pulmonary_artery_pressure, NaN Count: 35
Column: hemoliz, NaN Count: 33
Column: NOT, NaN Count: 32
Column: complaint, NaN Count: 20
Column: lipemi, NaN Count: 13
Column: CK-MB, NaN Count: 10
Column: pot, NaN Count: 6
Column: ikter, NaN Count: 5
Column: eos, NaN Count: 5
Column: BNP, NaN Count: 5
Column: mono, NaN Count: 4
Column: folat, NaN Count: 4
Column: ldl, NaN Count: 4
Column: sgpt, NaN Count: 4
Column: bun, NaN Count: 3
Column: baso, NaN Count: 3
Column: baso_hatch, NaN Count: 3
Column: TROPONIN I, NaN Count: 3
Column: diastolic_pressure, NaN Count: 2
Column: colestrol, NaN Count: 2
Column: crea, NaN Count: 2
Column: tri, NaN Count: 2
Column: systolic_pressure, NaN Count: 2
Column: hdlk, NaN Count: 2
Column: vldl, NaN Count: 2
Column: weight, NaN Count: 2
Column: eos_hatch, NaN Count: 2
Column: mpv, NaN Count: 2
Column: rdwsd, NaN Count: 1
Column: rdwcv, NaN Count: 1
Column: pct, NaN Count: 1
Column: lym, NaN Count: 1
Column: ne, NaN Count: 1
Column: pdw, NaN Count: 1
Column: rbc, NaN Count: 1
Column: plt, NaN Count: 1
Column: mcv, NaN Count: 1
Column: hgb, NaN Count: 1
Column: hct, NaN Count: 1
Column: t4, NaN Count: 1
Column: mono_hatch, NaN Count: 1
Column: neu, NaN Count: 1
Column: DM, NaN Count: 1
Column: HL, NaN Count: 1
Column: HT, NaN Count: 1
Column: mch, NaN Count: 1
Column: mchc, NaN Count: 1
Column: height, NaN Count: 1
Column: KOAH, NaN Count: 1
Column: wbc, NaN Count: 1
Column: bilirubin_dir, NaN Count: 1
Column: KC HST, NaN Count: 1
Column: KBY, NaN Count: 1
Column: cal, NaN Count: 1
Column: KAH, NaN Count: 1
Column: HbA1C, NaN Count: 1
Column: tsh, NaN Count: 1
Column: lym_hatch, NaN Count: 1
Column: result, NaN Count: 0
Column: identification_number, NaN Count: 0
Column: id, NaN Count: 0
Column: age, NaN Count: 0
Column: sex, NaN Count: 0
Column: ascending_aorta, NaN Count: 0
Column: aortic_root, NaN Count: 0
Column: end_systolic_diameter, NaN Count: 0
Column: injection_fraction, NaN Count: 0
Column: back_wall, NaN Count: 0
Column: right_atrium_size, NaN Count: 0
Column: left_atrium_size, NaN Count: 0
Column: report_date, NaN Count: 0
Column: patient, NaN Count: 0
Column: patient_name, NaN Count: 0
Column: patient_no, NaN Count: 0
Column: e_septal, NaN Count: 0
Column: visual_systolic_function, NaN Count: 0
Column: septum, NaN Count: 0
Column: bilirubin_in, NaN Count: 0
Column: aks, NaN Count: 0
Column: clor, NaN Count: 0
Column: sod, NaN Count: 0
Column: amilaz, NaN Count: 0
Column: bilirubin_tot, NaN Count: 0
Column: sgot, NaN Count: 0
Column: gfr, NaN Count: 0
Column: t3, NaN Count: 0
Column: b12, NaN Count: 0

In [17]:
merge_df = merge_df.drop(columns=['application_date', 'preliminary_diagnosis',
                                  'end_diastolic_diameter', 'practicing_doctor', 
                                  'requesting_section', 'e_a', 'deceleration_time',
                                  'e_lateral', 'ivrz', 'hatchway_speed', 'local_wall', 'tapse',
                                  's_val', 'diastolic_diameter', 'systolic_pulmonary_artery_pressure',
                                  'hemoliz', 'NOT'])

In [18]:
merge_df

,patient,patient_name,patient_no,report_date,age,sex,aortic_root,ascending_aorta,end_systolic_diameter,injection_fraction,...,baso_hatch,t3,t4,tsh,folat,b12,TROPONIN I,CK-MB,BNP,HbA1C
0,3,VEZİR YAŞAR,2022238881,2023-10-18 16:08:33,60,E,28,33,25,60,...,"0,02","3,41","1,37","1,03","7,4",407,"15,8","1,1","23,6",106.0
1,23,SARAYNAZ GÖKBAŞİ,2009334527,2023-10-20 15:05:57,76,K,25,30,20,65,...,"0,02","2,61","0,91","3,69","9,4",290,"4,4",NaN,"70,3",35.0
2,25,HÜSNİYE OLAM,2009444601,2023-10-20 16:38:37,63,K,30,38,35,60,...,"0,04","2,9","1,12","0,25","5,3",195,"3,9","2,1",NaN,75.0
3,27,İLHAMİ YEŞİL,2009392364,2023-10-23 15:43:41,57,E,28,31,28,65,...,"0,06","3,1","0,86","1,15","6,2",635,"3,5","1,3",NaN,37.0
4,22,HANİFE ÇİÇEK,2010223331,2023-10-20 14:57:16,65,K,30,40,38,60,...,"0,07","2,71","0,92","3,23","13,3",509,"2,9","1,1","224,6",40.0
5,19,MURAT KARAYEL,2013115566,2023-10-20 14:08:10,47,E,31,31,22,65,...,"0,01","3,34",NaN,"0,51","4,4",264,"1,3","1,1","11,8",54.0
6,14,YUSUF TURHAN,2010268947,2023-10-19 15:40:13,66,E,30,33,22,65,...,"0,04","3,21","1,12","0,5",NaN,334,"3,8","0,8","44,5",26.0
7,13,DURMUŞ ÖZTÜRK,2009166562,2023-10-19 15:32:36,51,E,23,32,25,60,...,"0,02","2,92","0,88","2,65","4,5",166,"1,8","1,2",NaN,25.0
8,41,HACER BİNALİOĞLU,2010361726,2023-10-27 15:57:16,64,K,27,33,38,60,...,"0,02","2,39","0,82","4,32","7,8",335,14,"3,8","27,9",38.0
9,31,İDRİS SERT,2009070964,2023-10-25 15:37:47,56,E,28,34,28,65,...,"0,05","3,01","0,93","1,4","6,9",300,"3,1","1,4","18,9",27.0
10,29,NÜSRET GÖKÇE,2016119682,2023-10-23 16:00:13,62,E,28,33,31,60,...,"0,04","3,19","1,09","1,49","8,4",220,"4,9",NaN,"62,2",57.0
11,8,LÜTFİYE ADALI,2016213502,2023-10-18 15:33:01,58,K,29,34,25,60,...,"0,02","2,73","1,33","2,5","5,4",474,"2,1","2,8","54,4",41.0
12,39,ERDOĞAN YILMAZ,2010027126,2023-10-27 15:42:42,56,E,22,36,23,60,...,"0,04","3,13","0,97","1,5","5,1",333,"3,7","1,2","27,5",34.0
13,40,AYŞE YILDIRIM,2009345536,2023-10-27 15:48:29,59,K,32,38,30,60,...,"0,03","2,88","0,82","1,47","8,9",195,"0,7","1,3","23,8",51.0
14,10,KADİR YALÇIN,2023131335,2023-10-19 10:59:43,65,E,30,37,35,60,...,"0,03","2,71","1,25","1,2","4,3",188,"4,6","0,7","42,8",43.0
15,17,ŞAHİDE NİYAZOĞLU,2014262020,2023-10-20 11:15:00,59,K,28,30,26,65,...,"0,02","2,73","0,93","1,41","4,2",128,"2,7","2,5","47,6",39.0
16,2,MÜNÜR ÇAPKINLAR,2010173740,2023-10-18 09:51:52,62,E,32,40,28,60,...,"0,03","3,23","0,97",NaN,"5,7",252,"2,8","1,4","17,6",41.0
17,1,NURCAN TANTUR,2009001287,2023-10-18 09:37:37,53,K,26,34,23,65,...,"0,03","3,04","1,09","1,78","5,5",231,"4,9","1,4",86,52.0
18,34,SÜHEYLA OKUMUŞ,2009416786,2023-10-25 16:02:41,59,K,27,28,23,60,...,"0,01","3,16","1,1","0,7",NaN,260,"1,8","1,1","10,5",41.0
19,21,AZİZE OPUZ,2009483173,2023-10-20 14:38:03,71,K,29,37,33,60,...,"0,06","2,81","1,42","0,17","5,6",362,"3,9",NaN,"279,3",38.0
20,12,EMİNE ARINÇ,2006076436,2023-10-19 15:25:55,74,K,29,34,33,60,...,"0,06","2,62","0,79","4,79","10,4",106,"14,7","3,4","149,5",40.0
21,38,GÜLSİMET TURHANER,2009563351,2023-10-27 15:35:33,61,K,30,36,27,60,...,"0,04","2,93","0,9","0,74","4,5",224,"2,3","2,1","26,1",28.0
22,37,NAZMİYE MÜMİNOĞLU,2022030986,2023-10-25 16:31:31,69,K,29,30,26,60,...,NaN,"2,68","1,22","0,25","2,3",274,"2,5",NaN,"38,4",46.0
23,26,TÜLAY BAKIR,2011043793,2023-10-23 15:35:42,48,K,21,28,23,60,...,"0,03","3,01","0,85","2,21",NaN,381,"1,5",NaN,"23,9",42.0
24,5,OĞUZHAN GÜLOĞULLARI,2010287204,2023-10-18 14:23:58,25,E,26,23,32,65,...,"0,03","3,18","0,94","2,84","4,1",251,"3,8",NaN,"24,7",19.0
25,7,SEVDA UYSAL,2011185275,2023-10-18 15:03:32,54,K,27,31,33,60,...,"0,06","3,15","1,04","1,2","5,8",414,18,NaN,"96,2",106.0
26,32,İZZET SOYLU,2017452619,2023-10-25 15:48:04,55,E,31,36,32,60,...,"0,04","3,22","0,94","1,08","5,3",306,NaN,"4,9",NaN,38.0
27,15,EROL ALTUNKAYA,2009122381,2023-10-19 15:47:43,50,E,24,32,31,60,...,"0,02","1,52","1,13","0,56","6,6",174,"3,2","5,5",NaN,33.0
28,28,HACI ERDAL,2017073268,2023-10-23 15:51:17,59,E,26,33,33,60,...,"0,02","2,9","0,93","1,24","5,8",237,"3,3","2,7","12,7",65.0
29,16,LEYLA YAĞMUR,2006549471,2023-10-19 15:57:46,63,K,29,43,23,60,...,NaN,"3,01","0,87","1,5","7,7",358,"1,4","1,3",58,37.0
30,24,NEZAHAT YILDIRIM,2009480173,2023-10-20 16:28:00,67,K,26,30,30,60,...,"0,05","2,67","1,03","2,26","8,1",193,"2,5","1,6","49,5",56.0
31,33,HATUN DOKMUŞ,2009387926,2023-10-25 15:54:22,48,K,30,40,32,60,...,"0,02","2,56","1,08","0,97","7,7",243,"1,3","0,9","17,6",42.0
32,20,AHMET ÖRS,2006630512,2023-10-20 14:18:06,70,E,27,36,50,40,...,"0,02","2,76","0,92","0,91","8,1",168,"130,2",NaN,"351,3",83.0
33,9,SELAMİ KOŞUCU,2013025887,2023-10-18 15:40:07,48,E,26,30,25,60,...,"0,05","3,06","0,96","0,91","3,3",380,"3,9",NaN,"11,6",NaN
34,11,HANIM YILMAZ,2011191666,2023-10-19 15:15:34,65,K,28,35,23,60,...,"0,03","2,59","0,89","2,34","6,2",187,NaN,"1,2",44,39.0
35,18,NERİMAN GÜLER,2009093536,2023-10-20 09:45:28,71,K,26,34,23,65,...,NaN,"2,34","0,88","6,34","3,1",943,"1,5","2,4","16,7",43.0
36,35,NURAY KABA,2013167794,2023-10-25 16:12:15,41,K,28,30,30,60,...,"0,04","3,35","0,87","1,34",NaN,399,"0,9","0,8",30,35.0
37,4,MENŞURE ÇİNİCİ,2017221642,2023-10-18 14:08:18,59,K,26,30,35,60,...,"0,01","2,71","1,08","2,25","8,1",335,"1,9",NaN,"26,8",46.0
38,36,YUSUF SAÇLI,2009587082,2023-10-25 16:21:59,59,E,27,32,40,50,...,"0,09","2,93","1,12","1,04","3,4",295,"10,1","4,9","129,8",38.0
39,6,SENFİNAZ ARAS,2010216741,2023-10-18 14:46:20,68,K,27,33,32,60,...,"0,03","3,67","1,35","0,01","6,1",163,NaN,"0,8","90,4",114.0
40,30,FERİDE GÖZALAN,2012181508,2023-10-23 16:08:47,58,K,26,36,30,40,...,"0,05","1,98","1,24","1,33","5,5",231,"31,9","16,6","228,8",58.0

In [19]:
merge_df.to_csv('merge_df.csv')

In [ ]:
X = iris.data
y = iris.target

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.decomposition import PCA
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

import matplotlib.pyplot as plt
plt.scatter(X_pca[:, 0], X_pca[:, 1], c=y)
plt.xlabel('PCA X')
plt.ylabel('PCA Y')
plt.show()