In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('datasets/patient.csv')
df = df.drop('Unnamed: 0', axis=1)
df

    patient          result
0         3              LA
1        23  LA DİLATASYONU
2        25  LA DİLATASYONU
3        27  LA DİLATASYONU
4        22  LA DİLATASYONU
..      ...             ...
82       36     HAFİF MY/TY
83       30         ORTA MY
84       30        İLERİ TY
85        1     HAFİF MY/TY
86       16        HAFİF MY

[87 rows x 2 columns]

In [15]:
df[df['result']=='SOL VENTRİKÜL HİPERTROFİSİ']

    patient                      result
16        2  SOL VENTRİKÜL HİPERTROFİSİ
47       27  SOL VENTRİKÜL HİPERTROFİSİ
54       39  SOL VENTRİKÜL HİPERTROFİSİ
56        2  SOL VENTRİKÜL HİPERTROFİSİ
57        1  SOL VENTRİKÜL HİPERTROFİSİ
60       12  SOL VENTRİKÜL HİPERTROFİSİ
64       16  SOL VENTRİKÜL HİPERTROFİSİ
67       11  SOL VENTRİKÜL HİPERTROFİSİ
68       18  SOL VENTRİKÜL HİPERTROFİSİ
73       22  SOL VENTRİKÜL HİPERTROFİSİ

In [6]:
df.result.value_counts()

result
LA DİLATASYONU                                                            26
LA                                                                        15
SOL VENTRİKÜL HİPERTROFİSİ                                                10
HAFİF MY                                                                   7
HAFİF TY                                                                   4
ASENDAN AORTADA DİLATASYON                                                 4
HAFİF MY/TY                                                                4
PHT                                                                        2
ORTA MY                                                                    2
POSTERİOR HİPOKİNETİK                                                      1
PLEVRAL MAİ İZLENDİ, PERİKARDİYEL MAİ İZLENDİ, FİBRİN BANTLARI İZLENDİ     1
MİNİMAL TY                                                                 1
RA                                                                         1
MİTRAL ANULUS KALSİFİK                                                     1
SAĞ KALP BOŞLUKLARI NORMAL                                                 1
NORMOFONKSİYONE MVR                                                        1
NORMOFONKSİYONE AVR                                                        1
AORT METALİK PROTEZ KAPAK                                                  1
İAS İNCE, HAREKETLİ, RENKLİ DOPPLER İLE GEÇİŞ İZLENMEDİ                    1
SAĞ YAPILAR İÇERSİNDE LEAD İZLENDİ                                         1
HAFİF AY                                                                   1
İLERİ TY                                                                   1
Name: count, dtype: int64

In [3]:
df.groupby('patient')

In [8]:
dummies = pd.get_dummies(df['result'], prefix='result')
df = pd.concat([df, dummies], axis=1)
df = df.drop('result', axis=1)
df

,patient,result_AORT METALİK PROTEZ KAPAK,result_ASENDAN AORTADA DİLATASYON,result_HAFİF AY,result_HAFİF MY,result_HAFİF MY/TY,result_HAFİF TY,result_LA,result_LA DİLATASYONU,result_MİNİMAL TY,...,result_PHT (SPAB: 40 MMHG),result_PHT (SPAB: 50 MMHG),"result_PLEVRAL MAİ İZLENDİ, PERİKARDİYEL MAİ İZLENDİ, FİBRİN BANTLARI İZLENDİ",result_POSTERİOR HİPOKİNETİK,result_RA,result_SAĞ KALP BOŞLUKLARI NORMAL,result_SAĞ YAPILAR İÇERSİNDE LEAD İZLENDİ,result_SOL VENTRİKÜL HİPERTROFİSİ,"result_İAS İNCE, HAREKETLİ, RENKLİ DOPPLER İLE GEÇİŞ İZLENMEDİ",result_İLERİ TY
0,3,False,False,False,False,False,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
1,23,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,25,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,27,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,22,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,36,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
85,30,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
86,30,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
87,1,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
88,16,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [8]:
df

    patient          result
0         3              LA
1        23  LA DİLATASYONU
2        25  LA DİLATASYONU
3        27  LA DİLATASYONU
4        22  LA DİLATASYONU
..      ...             ...
82       36     HAFİF MY/TY
83       30         ORTA MY
84       30        İLERİ TY
85        1     HAFİF MY/TY
86       16        HAFİF MY

[87 rows x 2 columns]

KeyError: "None of [Index([(False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False, True, False, False, False, False, False, False, True, False, True, True, False, False, True, False, False, False, True, False, False, True, True, False, False, False, False, True, False, False, False, False, False, False, False, False, False, False, False, False, False)], dtype='object')] are in the [columns]"

In [ ]:
LA DİLATASYONU                                                            26
LA                                                                        15
SOL VENTRİKÜL HİPERTROFİSİ                                                10

In [7]:
def apply_dummies(group):
    dummies = pd.get_dummies(group['result'], prefix='result')
    group = pd.concat([group, dummies], axis=1)
    group = group.drop('result', axis=1)
    return group

# Apply the function to each group and combine the results
df_grouped = df.groupby('patient').apply(apply_dummies).reset_index(drop=True)

# Display the resulting DataFrame
df_grouped

/tmp/ipykernel_6312/3478272728.py:8: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_grouped = df.groupby('patient').apply(apply_dummies).reset_index(drop=True)

,patient,result_HAFİF MY/TY,result_LA DİLATASYONU,result_PHT,result_SOL VENTRİKÜL HİPERTROFİSİ,result_ASENDAN AORTADA DİLATASYON,result_LA,result_HAFİF MY,result_NORMOFONKSİYONE AVR,result_NORMOFONKSİYONE MVR,...,result_HAFİF TY,result_SAĞ KALP BOŞLUKLARI NORMAL,result_ORTA MY,result_AORT METALİK PROTEZ KAPAK,result_MİTRAL ANULUS KALSİFİK,result_SAĞ YAPILAR İÇERSİNDE LEAD İZLENDİ,result_İLERİ TY,result_RA,"result_İAS İNCE, HAREKETLİ, RENKLİ DOPPLER İLE GEÇİŞ İZLENMEDİ",result_POSTERİOR HİPOKİNETİK
0,1,False,True,False,False,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,False,False,False,True,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,False,False,True,False,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,True,False,False,False,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,NaN,NaN,NaN,True,False,False,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
82,38,NaN,NaN,NaN,NaN,NaN,False,True,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,39,NaN,True,NaN,False,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,39,NaN,False,NaN,True,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,40,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
86,41,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN